
/* Each new term in the Fibonacci sequence isgenerated by adding
the previous two terms. By starting with 1 and 2, 
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values
do not exceed four million, find the sum of the even-valued terms. */



function fibonacci(n) {
   if (n < 2){
     return 1;
   }else{
     return fibonacci(n-2) + fibonacci(n-1);
   }
}
var answer = 0;
var arr = [];
var j = 0;
while (fibonacci(j) <15) {
    var value = 0;
    value += fibonacci(j);
    if(value % 2 === 0) {
        arr.push(value);
        answer += value;
    }
     var termValue = j ;
    j++;
}
console.log("the term value is: " + termValue)
console.log("The set of even fibanacci numbers is: " + arr);
console.log("The sum of the even fibonacci numbers is " + answer);
